color_map = {'steps':'goldenrod',
'average_heart_rate_in_beats_per_minute':'tomato',
'quest_sport_time':'sandybrown',
'awake_duration_in_seconds':'darkturquoise',
'quest_sleep_quality':'darkcyan',
'quest_sleep_time':'mediumseagreen',
'quest_mood':'slateblue',
'quest_stress':'darkorchid',
'quest_meetings':'purple', 
'rest_stress_duration_in_seconds':'slateblue',
'screen_duration_total': '#ff99ff',
'screen_daily_count':'#ff3399'  ,
'rest_stress_duration_in_seconds':'darkorchid',
'activity_stress_duration_in_seconds':'purple',
'max_stress_level':'mediumseagreen',
'bluetooth_distinct_names':'#ff3399',
'still_ratio':'#ff6666',
'deep_sleep_duration_in_seconds':'purple',
'sleep_start_hour':'#00cc66',
'screen_during_night_count':'#00cc66'
 }
